### ISSUE TITLE
help, please bigo.tv version

### ISSUE THREAD

**Issue by senhor-R** [EnterGin/Auto-Stream-Recording-Twitch#1]
help, please bigo.tv version

**Comment by EnterGin** [comment]
I've cheked this site.

I don't really know about API, but tomorrow I will try to make something that should work properly.

**Comment by senhor-R** [comment]
thank you, you are God

**Comment by EnterGin** [comment]
Hello!

Sorry for late answer, I was really busy these days.
Here your bigo.tv version.

[Auto_Recording_Twitch_Bigo.zip](https://github.com/EnterGin/Auto-Stream-Recording-Twitch/files/4432266/Auto_Recording_Twitch_Bigo.zip)

**You must install bs4 module. Type in command prompt: "pip install bs4"**

I can't fetch stream's name because bigo don't have API and there is no stream's name on the stream page.

Also I can't test it well because I don't use bigo. If you face any bugs, feel free to write me.

**Comment by senhor-R** [comment]
you are awesome

**Comment by senhor-R** [comment]
help me.

Traceback (most recent call last):
  File "Auto_Recording_Twitch_Bigo.py", line 166, in <module>
    main(sys.argv[1:])
  File "Auto_Recording_Twitch_Bigo.py", line 147, in main
    twitch_recorder = TwitchRecorder()
  File "Auto_Recording_Twitch_Bigo.py", line 52, in __init__
    self.username = "".join(x for x in self.username if x.isalnum() or not x in ["/","\\",":","?","*",'"',">","<","|"])
TypeError: 'NoneType' object is not iterable

**Comment by EnterGin** [comment]
Provide me bigo ID, please

**Comment by EnterGin** [comment]
Change 51 line of code:
`self.username = str(soup.findAll(attrs={"class":"hosts_name"})[1].string)`

**Comment by senhor-R** [comment]
http://www.bigo.tv/324517178

**Comment by senhor-R** [comment]
File "Auto_Recording_Twitch_Bigo.py", line 52
    self.username = "".join(x for x in self.username if x.isalnum() or not x in ["/","\\",":","?","*",'"',">","<","|"])
       ^
SyntaxError: invalid syntax

**Comment by senhor-R** [comment]
the last error, help.

**Comment by EnterGin** [comment]
Usage:
Add bigo ID (**NOT LINK ONLY ID**) in 36 line, eg: `self.bigo_id = "324517178"`
Also you can use it by command prompt, eg: `python Auto_Recording_Twitch_Bigo.py -u 324517178`

[Auto_Recording_Twitch_Bigo.zip](https://github.com/EnterGin/Auto-Stream-Recording-Twitch/files/4450517/Auto_Recording_Twitch_Bigo.zip)

**Comment by senhor-R** [comment]
thank you master

**Comment by senhor-R** [comment]
live finished.
live online.

don't continue downloading, can't find the file?
are the stickers causing the error?

sorry my bad english

error: Failed to open output: D:\\laptop/recorded/🥕 Shy 🕊/20200408_(18-50)_379581296_🥕 Shy 🕊.mp4 ([Errno 2] No such file or directory: 'D:\\laptop/recorded/🥕 Shy 🕊/20200408_(18-50)_379581296_🥕 Shy 🕊.mp4')

**Comment by EnterGin** [comment]
Do you have "laptop" folder on your D:\ drive?
You should **set your paths**, root path and path to ffmpeg.exe. Also you need to put your **timezone**. Please edit py file using **notepad++**
![Screenshot_20200409-030042__01](https://user-images.githubusercontent.com/51099894/78841569-bf8c5f80-7a0e-11ea-8ef4-3a915f4eb32e.jpg)

**Comment by senhor-R** [comment]
i use linux

**Comment by EnterGin** [comment]
Oh. 
This project didn't designed for Linux tbh, so I don't clearly know what you have to do.
But atleast try to set your root path and timezone.

**Comment by senhor-R** [comment]
working perfectly on Linux

**Comment by senhor-R** [comment]
think about creating a streamers list .txt for multiple downloads?

Thanks.

**Comment by EnterGin** [comment]
I'm just using number of copies of the script with different usernames in it. You can run them all at one time and they will work just fine. It is better for reliability.

**Comment by senhor-R** [comment]
thank you master

**Comment by senhor-R** [comment]
what to study to be able to script like you?

**Comment by EnterGin** [comment]
Just analyse someone else's code and try to find answers to your questions on google/stackoverflow 😄

**Comment by senhor-R** [comment]
is any other plugin possible in this script?
like these plugins: https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins

**Comment by EnterGin** [comment]
So it is actually easy to make any of these, because my script use streamlink to record streams.
