### ISSUE TITLE
short_folder description could be wrong

### ISSUE THREAD

**Issue by Jaroki42** [EnterGin/Auto-Stream-Recording-Twitch#12]
Hi there,

I was setting up your python script and was confused of the description in the comment of short_folder.
When I left it on 0 the folder in the processed-folder was named with date, title etc., but when I set it to 1 it named the folder to only date. Am I not understanding the description?

self.short_folder       = 0                                # 0 - only date in processed VOD folder, 1 - date, title, game and username in processed VOD folder

**Comment by EnterGin** [comment]
Hello.

It is actually wrong, thanks for noticing.
