### ISSUE TITLE
404 Client Error

### ISSUE THREAD

**Issue by VirtuallyJesse** [EnterGin/Auto-Stream-Recording-Twitch#13]
Hello, program was working great until today. Now it is returning:

404 Client Error: Not Found for url: https://api.twitch.tv/kraken/users?login=channelname

Has anyone else encountered this issue?

**Comment by EnterGin** [comment]
Kraken is gone 😂
Seems like it's time to move to Helix....

**Comment by EnterGin** [comment]
I have some implementation for helix. Tomorrow I will commit it.
Unfortunately you have to register your app and get your own client id and client secret 😥

**Comment by EnterGin** [comment]
Fixed in latest commit. More tests needed before release.
