### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fidelitas1894** [EnterGin/Auto-Stream-Recording-Twitch#2]
Hey!
first i want to thank you for your great work with this.
i used this since a month with out any problems.
i've had the error:
`unexpected error. Try to check internet connection or client-id. Will try again in 1.0 seconds.`
today. checked if there is a new version and installed the version from 7 days ago.
but i still get the same error.

**Comment by EnterGin** [comment]
Hey!
Firstly, it works fine for me at this moment.
Secondly, try to ping "api.twitch.tv".
It's might be problem with your internet provider.

**Comment by fidelitas1894** [comment]
i can ping the api without any problems.

i can also open

`https://api.twitch.tv/kraken/channels/juergenzimmermann?client_id=kimne78kx3ncx6brgo4mv6wki5h1ko`

in my browser by passing your developer ID as parameter

but when i start the twitch-recorder,py

it continues throwing me this msg:

`15h45m52s   unexpected error. Try to check internet connection or client-id. Will try again in 10.0 seconds.
15h46m02s   unexpected error. Try to check internet connection or client-id. Will try again in 10.0 seconds.`

also i noticed that this time idont need to get my own authtoken?

**Comment by EnterGin** [comment]
Can you provide your version of the script?

**Comment by EnterGin** [comment]
You don't need oauth token since Twitch changed API endpoints. [Streamlink also removed oauth in new version.](https://github.com/streamlink/streamlink/pull/2846) Because of this, you cannot record subscriber-only streams.

**Comment by EnterGin** [comment]
Add `print(e)` command after 225 line of code. After that, it will be possible to understand what kind of problem arises.
![image](https://user-images.githubusercontent.com/51099894/80220851-2172d900-864d-11ea-9f50-6c5b7f4d3645.png)

**Comment by fidelitas1894** [comment]
> HTTPSConnectionPool(host='api.twitch.tv', port=443): Max retries exceeded with url: /kraken/channels/CHANNELNAME (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
> 17h00m54s   unexpected error. Try to check internet connection or client-id. Will try again in 10.0 seconds.

i edited the channelname out bc its lectures only (university, thansk to corona)

**Comment by EnterGin** [comment]
Try to download and install OpenSSL
https://slproweb.com/products/Win32OpenSSL.html

**Comment by fidelitas1894** [comment]
ok now i feel stupid :P

strange that it worked b4 tho.

Thanks for your awesome job!! and sorry for the trouble!
