### ISSUE TITLE
Question about game name

### ISSUE THREAD

**Issue by john2545** [EnterGin/Auto-Stream-Recording-Twitch#21]
I have no idea about fetching game id from VODs and kinda confused of which game name do i get in filename when there are multiple games in single VOD.

When VOD has multiple chapter(like just chatting, game1, game2, game3, etc), does it get last game id of the VOD?

is it possible to get game id from the longest chapter or the first chapter?

**Comment by EnterGin** [comment]
Hi!
VOD main game is always latest on the stream. 
Fun fact: Helix API doesn't have game id/game name in VOD request. 
That's why currently after stream recording we have to fetch stream info again to get latest game name.

**Comment by john2545** [comment]
> Hi!
> VOD main game is always latest on the stream.
> Fun fact: Helix API doesn't have game id/game name in VOD request.
> That's why currently after stream recording we have to fetch stream info again to get latest game name.

Wow... I thought that was from twitch api. Thanks for the answer.
