### ISSUE TITLE
Doesn't work with private oauth token

### ISSUE THREAD

**Issue by Ethanland** [EnterGin/Auto-Stream-Recording-Twitch#22]
The old version of Streamlink stopped working, so I updated to the newest version of Streamlink, and now if I put in an oauth token it just keeps giving a 401 error message. Removing the token seems to make it work again, although considering I run this in the background until a stream starts I won't know for sure until one starts

**Comment by EnterGin** [comment]
Hello!

It works for me at the moment. Can you provide any logs? Without token of course.

**Comment by Ethanland** [comment]
I don't know how to get a log, but like I said it works fine without a token, but with it it just keeps printing "[cli][error] Unable to open URL: https://gql.twitch.tv/gql (401 Client Error: Unauthorized for url: https://gql.twitch.tv/gql)".

**Comment by EnterGin** [comment]
Your private token isn't valid.
Make sure that you picked a right token.

**Comment by EnterGin** [comment]
Also. You should paste only token without any words and spaces.
Example:
![image](https://user-images.githubusercontent.com/51099894/104951077-eed6f080-59d2-11eb-8856-c9ce46830c13.png)

**Comment by Ethanland** [comment]
I'm not sure what I did differently, but now it's working. Sorry for bothering you with this.

**Comment by EnterGin** [comment]
No problem
