### ISSUE TITLE
Bug with starting downloading stream to output file when stream title has special signs.

### ISSUE THREAD

**Issue by domixinox** [EnterGin/Auto-Stream-Recording-Twitch#25]
First I thought this is something related with streamlink update but then I checked dowloading other stream with this script and everything was ok, so I found out this signs "(" , ")" were the problem, here is cmd output:
Auto Stream Recording Twitch v1.7.0
Configuration:
OS: Windows 10
Root path: E:\yt
Ffmpeg path: E:\yt
Timezone: Europe/Warsaw (2.0)
Chat downloading Disabled
VOD downloading Disabled
Checking for blank every 5.0 seconds. Record with best quality.
[cli][info] Found matching plugin twitch for URL twitch.tv/blank
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
error: Failed to open output: E:\yt\recorded\blank\20210328_13h03m17s_march chat bday (blank crossing D+144) !ig !youtube !vods
_Art_blank.mp4 ([Errno 22] Invalid argument: 'E:\\yt\\recorded\\blank\\20210328_13h03m17s_march chat bday blank crossing D+144) !ig !youtube !vods\n_Art_blank.mp4')
[cli][info] Closing currently open stream...
Recording stream is done. Fixing video file.
Skip fixing. File not found.
Fixing is done. Going back to checking..
[cli][info] Found matching plugin twitch for URL twitch.tv/blank
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
error: Failed to open output: E:\yt\recorded\blank\20210328_13h03m24s_march chat bday (blank crossing D+144) !ig !youtube !vods
_Art_blank.mp4 ([Errno 22] Invalid argument: 'E:\\yt\\recorded\\blank\\20210328_13h03m24s_march chat bday (blank crossing D+144) !ig !youtube !vods\n_Art_blank.mp4')
[cli][info] Closing currently open stream...
Recording stream is done. Fixing video file.
Skip fixing. File not found.
Fixing is done. Going back to checking..

**Comment by EnterGin** [comment]
I think there is another problem.
Will investigate.

**Comment by domixinox** [comment]
Well now I found out, after dowloading multiple streams with different titles, that this is related with any spcial signs "!" etc. I tried deleting every varaible "['title']" from script and everything works fine now.

**Comment by EnterGin** [comment]
You're a bit wrong. It's related to EOL symbol ```\n```.
I'm actually working on refactoring the code and I don't know when I will finish.

So I committed simple workaround to immediate fix.
