### ISSUE TITLE
Path to stream is too long.

### ISSUE THREAD

**Issue by moreavea** [EnterGin/Auto-Stream-Recording-Twitch#27]
"Path to stream is too long. (Max path length is 259 symbols) Stream will not be processed, please check root path."

I recently started getting this error and I'm not sure what changed or where to look to fix it. It was working great for a while but now anytime I try to use it I get the error.

**Comment by somenewacc** [comment]
Can you provide streams/streamers and video filename in recorded path?

**Comment by EnterGin** [comment]
Hello!
Can you give me a stream that causes error?
Also video filename in recorded folder would be helpful too
