### ISSUE TITLE
[feature request] end script after live has ended

### ISSUE THREAD

**Issue by hollisticated-horse** [EnterGin/Auto-Stream-Recording-Twitch#29]
It would be really cool to be able to specify to kill the script when a live has ended. Dunno if it's already done ?

**Comment by EnterGin** [comment]
Hello.

It's easy to make (`quit()` after 345 line (`subprocess.call`)) but it's not the goal of script.

If you need to quit after all the processings, you can rewrite processing logic a bit (I can help if you need it).

**Comment by hollisticated-horse** [comment]
@EnterGin I have no clue where to start, I know a little python and a tiny bit of ffmpeg but that's it :D It'd be rad if you could walk me through the broadstrockes :D 

I'm asking for the feature because when I set the script to start from a cronjob, it got the first stream but since after there where a few rebroadcasts it seems to have fucked my files and I got only 3/4 of the initial stream... (I couldn't kill properly the script that was running ...)
