### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Silergo** [EnterGin/Auto-Stream-Recording-Twitch#3]
Can you make docker image, please? Want to use it for synology.  Something like that - https://hub.docker.com/r/liofal/streamlink. But this one stop working recently :(

**Comment by EnterGin** [comment]
Do you need docker image of streamlink?

**Comment by EnterGin** [comment]
Seems like I got the problem

**Comment by EnterGin** [comment]
It's very easy to fix btw.

**Comment by EnterGin** [comment]
Check it out:
https://github.com/liofal/dockerimages/pull/1

You just need to change ```helix``` to ```kraken``` in ```streamlink-recorder.py```

**Comment by EnterGin** [comment]
Wait-wait. Some changes required

**Comment by EnterGin** [comment]
OK, now I'm done. You can check this pull.
Or you can copy this file. Hope this works.

[streamlink-recorder.zip](https://github.com/EnterGin/Auto-Stream-Recording-Twitch/files/4629632/streamlink-recorder.zip)

**Comment by EnterGin** [comment]
Feel free to write if you still have questions.

**Comment by Silergo** [comment]
Thanks. It's works.
