### ISSUE TITLE
Output status printing to new line instead of same line with Streamlink 5.0.1

### ISSUE THREAD

**Issue by crackerbear** [EnterGin/Auto-Stream-Recording-Twitch#32]
This is a minor problem, however with the newly released Streamlink 5.0.1 when downloading a stream, the download status gets printed on a new line every second instead of overwriting the same line so the console is filled with download messages i.e.:

```[download] Written 815.33 MiB to D:…6h44m19s_somestream_Just Chatting_streamer.ts (14m55s @ 791.20 KiB/s)
[download] Written 815.33 MiB to D:…6h44m19s_somestream_Just Chatting_streamer.ts (14m55s @ 791.23 KiB/s)
[download] Written 815.33 MiB to D:…6h44m19s_somestream_Just Chatting_streamer.ts (14m56s @ 791.15 KiB/s)
[download] Written 820.63 MiB to D:…6h44m19s_somestream_Just Chatting_streamer.ts (14m56s @ 1.02 MiB/s)
```
The strange thing is when I use Streamlink directly in a console bypassing your script (i.e. with the command `streamlink --hls-live-restart --twitch-disable-ads -o D:\test.mkv https://www.twitch.tv/streamer best`), I get the old expected behaviour where the status is updated on the same line.

I'm on Windows 10 and running Python 3.10.5 if that makes any difference.

**Comment by EnterGin** [comment]
Most likely Streamlink issue.
The script doesn't control output.
It just use ```subprocess.call()``` to run streamlink process.

**Comment by crackerbear** [comment]
Very weird that running Streamlink directly doesn't produce this behaviour. Oh well, thanks for checking!

**Comment by EnterGin** [comment]
> Very weird that running Streamlink directly doesn't produce this behaviour.

As I can see from that comment:
[cli.utils.progress: relative paths on Windows don't get truncated correctly](https://github.com/streamlink/streamlink/issues/4829#issuecomment-1250190244)
It can be reproduced with direct streamlink run.

**Comment by EnterGin** [comment]
And btw you have really short name for manual run: ```D:\test.mkv```, that's why you don't see an issue (this issue only appears with truncated names).

**Comment by crackerbear** [comment]
Interesting that the [5.0.1 changelog](https://github.com/streamlink/streamlink/releases/tag/5.0.1) says that the `cli.utils.progress: fix relative Windows paths` bug is fixed.

But you're right, if I expand the console window to show the full output status then it stays on that line rather than producing a new one.
