### ISSUE TITLE
name template changed. VOD download not working after stream ends (?) 

### ISSUE THREAD

**Issue by mouarflenoob** [EnterGin/Auto-Stream-Recording-Twitch#33]
Hello,

This started happening at the beginning of august. The file I get since then, do not contain the VOD id of the VOD of a stream the script downloaded.
So just before 08/10 I got a file named : 
20220810_(04-33)_1557509138_title...title_Category_channel-name.mp4      but since then I get : 
20220831_06h08m44s_title...title_Just Chatting_channel-name.mp4

Does anyone have any idea why this is happening ?
Also, the script is running on a Ubuntu 22.04 server, if you can point me towards where the logs might be that would also be a great help.

Thanks.

**Comment by EnterGin** [comment]
Hi.
The reason is pretty simple -- there is an error during obtaining VOD info, so file has it's original name.

There are no logging to file, logs only to stdout.
