### ISSUE TITLE
vod folder created twice, with different date in the name, every time

### ISSUE THREAD

**Issue by mouarflenoob** [EnterGin/Auto-Stream-Recording-Twitch#34]
Hello,

I do not download VODs.
Everytime a stream I am downloading ends, two processed folders are created, with different date in the name. I don't understand why. I check the date in my system and it seems to be correct.
I will attach a screenshot, it will be easier than me trying to explain it.

![Untitled_issue](https://user-images.githubusercontent.com/2085758/195114445-f95b5ea1-b2d5-4dcf-bce1-ac417d61db8e.png)

As you can see, the first folder is named 20221009_xxx, the second folder is named 20221011_xxx
The stream is from this morning, so about 12 hours ago, which means the correct date is the 11th. But everytime the stream gets saved in the wrong folder.
There is always the correct folder, with the accurate date, but empty, and the other folder is named at a date 2 days before, and that's where the mp4 file ends up.

Here is the date of my serveur screenshotted next to the clock of my windows desktop : 
![date](https://user-images.githubusercontent.com/2085758/195114456-b62fbaae-0353-4c53-87c4-06446e3ae133.png)

I also attached my config for the script (with private information redacted of course) : 
[Auto_config.txt](https://github.com/EnterGin/Auto-Stream-Recording-Twitch/files/9757152/Auto_config.txt)
Do you know why it's happenning? Should I keep looking for an issue with my system date ?

Thanks.

**Comment by random-videos** [comment]
I am also experiencing a similar problem. The dates on the processed files are usually 2 days off.

**Comment by mouarflenoob** [comment]
I retried on a new server and now it doesn't acts like this anymore. I don't know why it started doing this, but it's fixed now. If you have any idea why it was acting that way, don't hesitate to PM me :)
