### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by camjac251** [EnterGin/Auto-Stream-Recording-Twitch#5]
I was hesitant a bit to try this on my linux machine since I saw some windows things in here like cmd.exe. Could calls to Windows specific functions be removed and replaced with python counterparts that are cross platform?
Also If you are using ffmpeg, it might be better add it to your env path so it can be globally called. Or use something like scoop to manage it for you.

I was interested in the readme when it said `stream will not be cut at the beginning` which is something I've been looking to fix with my current implementation.

I wanted to ask how you implemented that.

**Comment by EnterGin** [comment]
I know nothing about Linux. Because of that, I can't make it capable since I use Windows. You can help if you know anything about it.

FFmpeg path already in ```self```, so I don't think that it is really needed.

Now I'm using streamlink's ```--retry-streams``` to try to fetch streams every second, it is better than relaunch streamlink every iteration because it is more reliable and less resource intensive. I don't use API to check online status since API is really slow.

**Comment by camjac251** [comment]
I just mean for universal usage.
I see it calling cmd.exe everywhere
https://github.com/EnterGin/Auto-Stream-Recording-Twitch/blob/7aa9becd3cea626ee5cd93b6b3fa55ff2634baf0/Auto_Recording_Twitch.py#L43
https://github.com/EnterGin/Auto-Stream-Recording-Twitch/blob/7aa9becd3cea626ee5cd93b6b3fa55ff2634baf0/Auto_Recording_Twitch.py#L137
https://github.com/EnterGin/Auto-Stream-Recording-Twitch/blob/7aa9becd3cea626ee5cd93b6b3fa55ff2634baf0/Auto_Recording_Twitch.py#L146

Wouldn't there be a python function for calling the OS shell? using subprocess and os?
https://docs.python.org/3/library/subprocess.html
https://janakiev.com/blog/python-shell-commands/




Is `streamlink --retry-streams` similar in time to the result as `streamlink -j twitch.tv/channel`?
I was recently told about that, someone parses the results of that for their script.

**Comment by EnterGin** [comment]
Yeah, I know about calling ```cmd.exe```. I would fix this if I know more about Linux. I can't even test it on Linux.

No. ```--retry-streams``` just trying to fetch m3u8 playlist every set time. Streamlink doesn't check user online status, so it's not depend on API.

**Comment by EnterGin** [comment]
Linux compatibility added in 1.6.0, Check out latest release.
Looking forward for your opinion. 😀
