### ISSUE TITLE
Recording cuts off at 24 hours?

### ISSUE THREAD

**Issue by crackerbear** [EnterGin/Auto-Stream-Recording-Twitch#7]
I don't know if this is a coincidence but a recording of mine got cut off at exactly 24 hours which makes me think there's some part of the code that enforces this.

Is it possible to extend this to 48 hours (maximum length of a Twitch VOD)?

**Comment by EnterGin** [comment]
This is a Twitch limitation. 

You can try to merge not processed parts. (just change .mp4 to .ts on recorded files) 
Once I tried to merge 2 parts of stream over 24h, but I couldn't do it without re-encoding. 
Another way - you can try to download VOD. 
I tried this too and timestamps were broken and stream wasn't playable. 

So it's not that easy but you still can try maybe it'll work for you.
