### ISSUE TITLE
Watch specific category?

### ISSUE THREAD

**Issue by blurengo** [EnterGin/Auto-Stream-Recording-Twitch#9]
I'm wondering if there's a way for it to do this on a specific twitch category/game.

**Comment by EnterGin** [comment]
In chosen way I see only one method to do this. 
Check category of VOD after recording. If category is unwanted - recorded file will be deleted.

**Comment by EnterGin** [comment]
If this is acceptable to you, then I can do it.

**Comment by blurengo** [comment]
that would be fine, i am trying to automate a script that 
1. records streams from specific category
2. then uploads to yt
lol

**Comment by EnterGin** [comment]
Sorry for the wait, unfortunately was busy all this time.
There is no good implementation on Helix for now, sorry.
